In [12]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [13]:
from tensorflow.keras.datasets import mnist

In [14]:
(X_train,y_train),(X_test,y_test) = mnist.load_data()

In [15]:
X_train.shape

(60000, 28, 28)

In [16]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [17]:
plt.imshow(X_train[0])

In [19]:
y_train[0]

5

In [20]:
X_train =X_train/255

In [21]:
X_test = X_test/255

In [22]:
X_train[0]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

ANN

In [39]:
from tensorflow.keras.layers import Dense,Flatten
from tensorflow.keras.models import Sequential

In [28]:
X_train_flat = X_train.reshape(60000,784)
X_test_flat = X_test.reshape(10000,784)


In [33]:
model = Sequential([
    Dense(128,input_shape=(784,),activation='relu'),
    Dense(10,activation='sigmoid')
])
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(X_train_flat,y_train,epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.8766 - loss: 0.4321
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9652 - loss: 0.1201
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9778 - loss: 0.0753
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9835 - loss: 0.0571
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9876 - loss: 0.0422


In [34]:
y_pred = model.predict(X_test_flat)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


In [35]:
 from tensorflow.math import confusion_matrix

In [36]:
y_pred_num = [np.argmax(i)for i in y_pred]

In [37]:
con_mat = confusion_matrix(labels=y_test,predictions=y_pred_num)

In [38]:
con_mat

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 970,    0,    2,    0,    0,    0,    2,    1,    3,    2],
       [   0, 1127,    1,    2,    0,    0,    3,    0,    2,    0],
       [   4,    3,  993,   12,    1,    0,    2,    8,    9,    0],
       [   0,    0,    1,  997,    0,    2,    0,    3,    3,    4],
       [   0,    0,    3,    1,  952,    1,    7,    7,    2,    9],
       [   2,    0,    0,   22,    1,  859,    2,    0,    5,    1],
       [   3,    3,    1,    1,    2,    3,  943,    1,    1,    0],
       [   1,    5,    9,    4,    0,    0,    0, 1000,    2,    7],
       [   2,    0,    1,   13,    0,    4,    4,    3,  943,    4],
       [   2,    2,    0,    7,    4,    1,    1,    9,    5,  978]])>

In [54]:
from tensorflow.keras.layers import Conv2D,Conv1D
from tensorflow import keras

In [55]:
model = Sequential([
    keras.layers.Conv2D(filters=32,kernel_size=(2,2),activation='relu',input_shape=(28,28,1)),
    keras.layers.MaxPool2D(),

    keras.layers.Conv2D(filters=32,kernel_size=(2,2),activation='relu'),
    keras.layers.MaxPool2D(),
    Flatten(),
    Dense(128,input_shape=(784,),activation='relu'),
    Dense(10,activation='sigmoid')
])
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(X_train,y_train,epochs=5)

C:\Users\Bala\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 19s 9ms/step - accuracy: 0.8838 - loss: 0.3827
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 18s 10ms/step - accuracy: 0.9808 - loss: 0.0624
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 17s 9ms/step - accuracy: 0.9876 - loss: 0.0395
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 17s 9ms/step - accuracy: 0.9920 - loss: 0.0261
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 18s 9ms/step - accuracy: 0.9932 - loss: 0.0210


In [57]:
y_pred = model.predict(X_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step


In [58]:
y_pred[0]

array([3.1718307e-03, 1.0809392e-01, 2.6016068e-01, 7.9095972e-01,
       3.0030266e-04, 2.1318519e-03, 2.0227529e-09, 9.9999923e-01,
       2.6229495e-01, 9.5894456e-01], dtype=float32)

In [59]:
y_test[0]

7